### ISSUE TITLE
bazel repository context has empty string for `native.bazel_version`

### ISSUE THREAD

**Issue by werkt** [bazel-contrib/setup-bazel#42]
Discovered this while debugging the following runs: https://github.com/buildfarm/buildfarm/actions/runs/11227508099/job/31209992929
This differs from my local installation (and every other one I've found) that reflects, for instance, 7.3.2 into the string "7.3.2", which is used by bazel_features to discover whether a ProtoInfo should be available globally.

There's a substantial amount of debug output in that run, but the notable piece is (see EOL for difference in version):

```
DEBUG: /home/runner/work/buildfarm/buildfarm/test_extension.bzl:10:10: Proto Info is struct(CcSharedLibraryInfo = <provider>, DefaultInfo = <function DefaultInfo>, JavaInfo = None, JavaPluginInfo = None, PackageSpecificationInfo = <function PackageSpecificationInfo>, ProtoInfo = None, PyCcLinkParamsProvider = None, PyInfo = None, PyRuntimeInfo = None, RunEnvironmentInfo = <function RunEnvironmentInfo>, __TestingOnly_NeverAvailable = None) for native.bazel_version=``
```

While a local environment that can extract `native.bazel_version` would print out there:
```
DEBUG: /home/werkt/dev/bazel-buildfarm/test_extension.bzl:10:10: Proto Info is struct(CcSharedLibraryInfo = <provider>, DefaultInfo = <function DefaultInfo>, JavaInfo = <provider>, JavaPluginInfo = <provider>, PackageSpecificationInfo = <function PackageSpecificationInfo>, ProtoInfo = <provider>, PyCcLinkParamsProvider = <provider>, PyInfo = <provider>, PyRuntimeInfo = <provider>, RunEnvironmentInfo = <function RunEnvironmentInfo>, __TestingOnly_NeverAvailable = None) for native.bazel_version=`7.3.2`
```

Note the version output at the end. Repo rule and bzlmod shenanigans available [here](https://github.com/buildfarm/buildfarm/commit/e210b02c52d48cd88c4365001c6ae832864310fe#diff-c9ca89f9835a74626ce7b8a26767e3ede6e9b50317b86176146ca610b3ab57ee)

Is it possible the bazel 7.3.2 (same thing happens with 7.3.1) is polluted in the version this retrieves? I tried this with and without bazelisk-cache, no change. How could the bazel this pulls differ like this?

**Comment by p0deje** [comment]
I am not sure I follow what is the issue there. Can you elaborate how you use the action and what's actually wrong?

**Comment by werkt** [comment]
We use the action to build and perform codeql analysis/validation.
The problem is that very-new @protobuf is using bazel version detection to determine the type to use for ProtoInfo, and this is in conflict with a legacy @googleapis repository using the deprecated @rules_proto.
The basic reproducer is that `bazel version` does not yield a well formed `Build label` like `7.3.2` (this is emblematic of the problem's effect internally, where `native.bazel_version` is aligned to this output), only on github actions images, for reasons I don't yet understand (I suspect some java injection).

This seems to go much deeper, as every actions image for ubuntu seems to exercise this problem, and it is easily reproducible. I'll bring it up perhaps with the actions/remote-images project.
